=== qhsy/supersport-supersport/dcom-user/src/main/resources/ufile/db/templet.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uhutu.com/xml/ufile/db" xmlns="http://www.uhutu.com/xml/ufile/db"
	xmlns:mstns="http://www.uhutu.com/xml/ufile/db" elementFormDefault="qualified">

	<xs:element name="db">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="data">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code"></xs:attribute>
									<xs:anyAttribute processContents="skip" />

								</xs:complexType>


							</xs:element>

						</xs:sequence>

					</xs:complexType>
					<xs:unique name="bookUnique">
						<xs:selector xpath="mstns:item" />
						<xs:field xpath="@code" />
					</xs:unique>


				</xs:element>
			</xs:sequence>
		</xs:complexType>



	</xs:element>

</xs:schema>

=== qhsy/supersport-supersport/dcom-user/src/main/resources/ufile/db/data-ZwPathInfo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<db xmlns="http://www.uhutu.com/xml/ufile/db" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uhutu.com/xml/ufile/db  templet.xsd">
	<data>
		<item code="dzpi45101001" nodeName="用户相关" parentCode="" />
		<item code="dzpi451010010001" nodeName="用户管理" parentCode="dzpi45101001" />
		<item code="dzpi4510100100010001" nodeName="用户基本信息" parentCode="dzpi451010010001"
			pageUrl="/zpage/pg/com_uhutu_dcom_user_z_page_UserInfoOperPage" pageIcon="glyphicon-th" />
		<item code="dzpi451010010002" nodeName="用户反馈" parentCode="dzpi45101001" />
		<item code="dzpi4510100100020001" nodeName="反馈信息" parentCode="dzpi451010010002"
			pageUrl="/zpage/pg/com_uhutu_dcom_user_z_page_MsgAdvicePage" pageIcon="glyphicon-exclamation-sign" />	
		<item code="dzpi45101002" nodeName="app相关" parentCode="" />
		<item code="dzpi451010020001" nodeName="app管理" parentCode="dzpi45101002" />
		<item code="dzpi4510100200010001" nodeName="app版本信息" parentCode="dzpi451010020001"
			pageUrl="/zpage/pg/com_uhutu_dcom_user_z_page_AppVersionInfoPage" pageIcon="glyphicon-phone" />
	</data>

</db>
